/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    Productcard: (typeof import('./src/components/productCard/productcard.vue'))['default']
    ProductList: (typeof import('./src/components/productList/productList.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
